### ISSUE TITLE
Why this error happen: "ERROR: Invalid requirement: --h5py @ file:///home/conda/feedstock_root/build_artifacts/h5py_1593217410434/work pip: error: no such option: --h5py"

### ISSUE THREAD

**Issue by FernandoHo** [VDelv/Attention-EEG#4]
Dear Delv,

I am coming to this problem when executing the command of "pip install -r requirements.txt".  Do you know any approach to fix this?

**Comment by VDelv** [comment]
Dear FernandoHo, 

Thanks for being interested in the project, I update the requirement.txt file (some library were stored locally on my disk that explains this issue), it is supposed to work now. 

However, for the installation of Pytorch and Pytorch Geometric follow the installation guide as mentioned in the readme. 

Best,

**Comment by FernandoHo** [comment]
Thank you so much for the reply VDelv! I have sent a request to use the dataset you provided in Zenodo, I hope it could be guaranteed.

**Comment by VDelv** [comment]
You're welcome, 
I accept the request for the dataset, don't hesitate to contact me by mail (victor.delvigne@umons.ac.be) if you have concerns, issues or advice. 

Wish u the best in your research
